### ISSUE TITLE
unsecured app

### ISSUE THREAD

**Issue by eramsorgr** [sirhypernova/friendzone#1]
this is is very unsecure. the bot token is included on the code!?!? WTF

**Comment by sirhypernova** [comment]
It's alright, we saw. The token had already been reset anyways.

**Comment by eramsorgr** [comment]
Hi nova lol

**Comment by unlimitedcoder2** [comment]
@sirhypernova please fix this issue

**Comment by sirhypernova** [comment]
It's an old token. It doesn't matter, and I don't plan on updating this.

**Comment by eramsorgr** [comment]
hi alex hi nova why are we still using this and not discord lmao

**Comment by unlimitedcoder2** [comment]
because I wanted to remind nova that the security issue was still a thing

**Comment by DebitCardz** [comment]
Please secure this asap
